### ISSUE TITLE
CONTTY connection unusably slow

### ISSUE THREAD

**Issue by sethm** [sethm/simh#3]
If a user attaches to the CONTTY port, the both the CONTTY session and the console session become unusably slow. This behavior is relatively new, so I hope that a `git bisect` can figure out what change introduced it.

**Comment by markpizz** [comment]
You intended to create this issue in your personal simh repo, right?

I may have introduced the problem you're seeing.  What minimal steps can I take to observe this personally?  Before trying to get me that, you may want to reproduce the problem yourself and then CTRL-E and look at the output of SHOW MUX.  It may be illuminating.

Recent changes which may be affecting you are that the TMXR library attempts to explicitly honor the programmed port speed for output.  Looking through your code, I see that the TMXR APIs you're using, should not have had any negative effects on your device.

Looking at your 3b2_iu.c code, I see that you're calling *tmxr_clear_modem_control_passthru*, but never calling *tmxr_set_modem_control_passthru*.  The call to the clear routine will therefore have no affect at all since the default starts as cleared.  

I also seem to see some strange logic on the transmit side.  Specifically, in iu_tx, you're 'outputting' the character to be transmitted, and then you say:
```
         /* The buffer is now empty, we've transmitted, so set TXR */
        p->stat |= STS_TXR;
        iu_state.istat |= (1 << (portno*4));

        /* Possibly cause an interrupt */
        sim_activate_abs(uptr, uptr->wait);
```
To me, this doesn't seem like it tracks how the hardware worked.  Specifically, I would expect that the these things would be done some time later (not in the absolute same instruction which initiated the transmit operation).  These things are normally done in the unit service routine along with generating interrupts when they're enabled.

To enable the TMXR speed control for your device you should call:
```
tmxr_set_line_unit (&contty_desc, 0, contty_rcv_unit);
t_stat tmxr_set_line_output_unit (&contty_desc, 0, contty_xmt_unit);
t_stat tmxr_set_console_units (&tti_unit, &tto_unit);
```
in one of your device reset routines.

**Comment by sethm** [comment]
Thanks for the guidance! This should now be completely fixed in the latest checkins.
